### ISSUE TITLE
Introduce new Tags API

### ISSUE THREAD

**Issue by sergeyfd** [distribution/distribution#2170]
This is a read map issue to cover implementation activity for the plan discussed in #1956. The plan is:

1. [ ] Move `/v2/<name>/tags/list` to `/v2/<name>/tags/_list` with a redirect for backward compatibility. (#2169)
2. [ ] Add new route `/v2/<name>/tags/<reference>` for a `DELETE` operation. This route will support only tag references. (#2169)
3. [ ] Add new route `/v2/<name>/manifests/_list` for `GET` operation to retrieve a list of digests in a given repo. I am not sure if this route is a best choice, may be adding `/v2/<name>/digests/_list` would be a better option. (#2199)

**Comment by sergeyfd** [comment]
@stevvooe Let's discuss item 3 from the list above. I did a POC that provides this new route:

`
$ curl -i -X GET -H "Accept: application/vnd.docker.distibution.manifest.v2+json" http://localhost:5000/v2/test/t1/digests/HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff
Date: Sun, 12 Feb 2017 00:45:59 GMT
Content-Length: 179

{"name":"test/t1","digests":["sha256:bb236a9cc831933c2b73f3402b67b51f2def5900514d52a2c2695c034ecf2aa5","sha256:86942f70cd992d0d33d6db048444bc7bb98718c0807a615212346ffada92157f"]}
`

So the questions are:

1. Is it Ok to introduce completely new route `/v2/<name>/digests/` or shall it be `/v2/<name>/manifests/` instead?
2. Should it return just a list of strings containing digests or returning a list of more something complex objects such as `{"MediaType/SchemaVersion": "...", "Digest": "..."}` would be better ?
3. Should we implement is as a different PR or as a part of #2169 ? Lots of changes go to the same files
4. Should we do it now or until after release 2.7 and target it for 2.8? It's yet another change for the API and the first one hasn't been accepted yet.

**Comment by stevvooe** [comment]
> Is it Ok to introduce completely new route /v2/<name>/digests/ or shall it be /v2/<name>/manifests/ instead?

`digests` doesn't really make sense here. Most things can have a digest and this end point returns manifests. For example, would you have a `/v2/<name>/ids/` endpoint? Probably not.

> Should it return just a list of strings containing digests or returning a list of more something complex objects such as {"MediaType/SchemaVersion": "...", "Digest": "..."} would be better ?

A list of descriptors is the natural return here, or even a manifest list.

> Should we implement is as a different PR or as a part of #2169 ? Lots of changes go to the same files

This should be a different PR. I'd like to see the other one merged soon.

> Should we do it now or until after release 2.7 and target it for 2.8? It's yet another change for the API and the first one hasn't been accepted yet.

Let's see how the process proceeds. No sense in making road map promises if we don't know the scope.

**Comment by sergeyfd** [comment]
First iteration of implementation for #3 is in #2199

**Comment by Dm3Ch** [comment]
@sergeyfd Hello! I see that there is a progress for first two points. But is there any progress with third point (list all manifests in repository)?

**Comment by sergeyfd** [comment]
@stevvooe It's in #2199

**Comment by Dm3Ch** [comment]
Thank you

**Comment by milosgajdos** [comment]
Closing as wildly outdated. Besides, the tag API is defined by https://github.com/opencontainers/distribution-spec and already implemented by this project
