### ISSUE TITLE
[Epic] OCI Conformance Review

### ISSUE THREAD

**Issue by pmengelbert** [distribution/distribution#3203]
# OCI Conformance Review

Please review this registry's conformance against the OCI Distribution Specification: https://github.com/opencontainers/distribution-spec

- [x] https://github.com/docker/distribution/issues/3230 **OCI Conformance: POST request with digest and blob should yield a 201**
    - [x] Pull request: https://github.com/docker/distribution/pull/3212 OCI: POST request with digest and blob should yield 201
- [x] https://github.com/docker/distribution/issues/3231 **OCI Conformance: GET request to blob URL from prior request should yield 200**
- [x] https://github.com/docker/distribution/issues/3141 **OCI Conformance: "Out-of-order blob upload should return 416"**
    - [x] Pull request: https://github.com/docker/distribution/pull/3227 OCI: add content range handling in patch blob
- [x] https://github.com/docker/distribution/issues/3232 **OCI Conformance: GET number of tags should be limitable by `n` query parameter**
    - [x] tracking issue: https://github.com/docker/distribution/issues/1936 HTTP API Tags Paginated not work
    - [x] tracking issue: https://github.com/docker/distribution/issues/2452 API different responses
    - [x] Pull request: https://github.com/docker/distribution/pull/3143 Add pagination on `/v2/<name>/tags/list`
- [x] https://github.com/docker/distribution/issues/3233 **OCI Conformance: GET start of tag is set by `last` query parameter**
    - [ ] Pull request: https://github.com/distribution/distribution/pull/3902 Fix `last` bug and optimise catalog function
- [x] https://github.com/docker/distribution/issues/3234 **DELETE request to manifest tag should return 202, unless tag deletion is disallowed (400/405)**

Below is a detailed summary of failures detected for this registry based on the automated test results found here: https://conformance.opencontainers.org/distribution-spec/#dockerdistribution

### Pull
(None)

##### Monolithic upload

<details>
    <summary><b>POST request with digest and blob should yield a 201</b> docker/distribution#3230 </summary>

See below for the exact failure details. To resolve this issue, your registry should return a `201 Created` response when a POST request is made containing a blob, and finalized by including the digest in the `digest` query parameter. At this point, the upload of the blob must be considered complete.

```
2020/07/10 06:16:27.287679 DEBUG
==============================================================================
~~~ REQUEST ~~~
POST  /v2/oci-conformance/distribution-test/blobs/uploads/?digest=sha256%3A66ad98165d38f53ee73868f82bd4eed60556ddfee824810a4062c4f777b20a5b  HTTP/1.1
HOST   : distribution:5000
HEADERS:
	Content-Length: 113
	Content-Type: application/octet-stream
	User-Agent: distribution-spec-conformance-tests
BODY   :
ewoJImFyY2hpdGVjdHVyZSI6ICJhbWQ2NCIsCgkib3MiOiAibGludXgiLAoJImNvbmZpZyI6IHt9LAoJInJvb3RmcyI6IHsKCQkidHlwZSI6ICJsYXllcnMiLAoJCSJkaWZmX2lkcyI6IFtdCgl9Cn0=
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 202 Accepted
RECEIVED AT  : 2020-07-10T06:16:27.287314442Z
TIME DURATION: 4.595105ms
HEADERS      :
	Content-Length: 0
	Date: Fri, 10 Jul 2020 06:16:27 GMT
	Docker-Distribution-Api-Version: registry/2.0
	Docker-Upload-Uuid: 8531111e-51bf-4ca1-8845-c4df29914e53
	Location: http://distribution:5000/v2/oci-conformance/distribution-test/blobs/uploads/8531111e-51bf-4ca1-8845-c4df29914e53?_state=*****
	Range: 0-0
	X-Content-Type-Options: nosniff
BODY         :

==============================================================================

Expected
    <int>: 202
to equal
    <int>: 201
```
</details>
<details>
<summary><b>GET request to blob URL from prior request should yield 200</b> docker/distribution#3231</summary>

This failure will likely be resolved when the above changes are made. Once a complete upload can be made via a POST request containing the blob in the body, and the digest in the `digest` query parameter, the blob will be found.
```
2020/07/10 06:16:27.291971 DEBUG
==============================================================================
~~~ REQUEST ~~~
GET  /v2/oci-conformance/distribution-test/blobs/sha256:66ad98165d38f53ee73868f82bd4eed60556ddfee824810a4062c4f777b20a5b  HTTP/1.1
HOST   : distribution:5000
HEADERS:
	User-Agent: distribution-spec-conformance-tests
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 404 Not Found
RECEIVED AT  : 2020-07-10T06:16:27.291606746Z
TIME DURATION: 2.412602ms
HEADERS      :
	Content-Length: 157
	Content-Type: application/json
	Date: Fri, 10 Jul 2020 06:16:27 GMT
	Docker-Distribution-Api-Version: registry/2.0
	X-Content-Type-Options: nosniff
BODY         :
{
   "errors": [
      {
         "code": "BLOB_UNKNOWN",
         "message": "blob unknown to registry",
         "detail": "sha256:66ad98165d38f53ee73868f82bd4eed60556ddfee824810a4062c4f777b20a5b"
      }
   ]
}

==============================================================================

Expected
    <int>: 404
to equal
    <int>: 200
```
</details>

##### Chunked upload

<details>

<summary><b>Out-of-order blob upload should return 416</b> docker/distribution#3141 </summary>

Chunked uploads must be uploaded in order. If they are not, the registry must consider the upload failed and return a `416 Range Not Satisfiable` response code.

```
2020/07/10 06:16:27.330987 DEBUG
==============================================================================
~~~ REQUEST ~~~
POST  /v2/oci-conformance/distribution-test/blobs/uploads/  HTTP/1.1
HOST   : distribution:5000
HEADERS:
	Content-Length: 0
	User-Agent: distribution-spec-conformance-tests
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 202 Accepted
RECEIVED AT  : 2020-07-10T06:16:27.33059849Z
TIME DURATION: 3.521604ms
HEADERS      :
	Content-Length: 0
	Date: Fri, 10 Jul 2020 06:16:27 GMT
	Docker-Distribution-Api-Version: registry/2.0
	Docker-Upload-Uuid: c28d1a36-b2af-4ffc-a058-cf7f2227ac15
	Location: http://distribution:5000/v2/oci-conformance/distribution-test/blobs/uploads/c28d1a36-b2af-4ffc-a058-cf7f2227ac15?_state=*****
	Range: 0-0
	X-Content-Type-Options: nosniff
BODY         :

==============================================================================

2020/07/10 06:16:27.335405 DEBUG
==============================================================================
~~~ REQUEST ~~~
PATCH  /v2/oci-conformance/distribution-test/blobs/uploads/c28d1a36-b2af-4ffc-a058-cf7f2227ac15?_state=*****  HTTP/1.1
HOST   : distribution:5000
HEADERS:
	Content-Length: 22
	Content-Range: 3-24
	Content-Type: application/octet-stream
	User-Agent: distribution-spec-conformance-tests
BODY   :
bG8sIGhvdyBhcmUgeW91IHRvZGF5Pw==
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 202 Accepted
RECEIVED AT  : 2020-07-10T06:16:27.335067895Z
TIME DURATION: 3.984104ms
HEADERS      :
	Content-Length: 0
	Date: Fri, 10 Jul 2020 06:16:27 GMT
	Docker-Distribution-Api-Version: registry/2.0
	Docker-Upload-Uuid: c28d1a36-b2af-4ffc-a058-cf7f2227ac15
	Location: http://distribution:5000/v2/oci-conformance/distribution-test/blobs/uploads/c28d1a36-b2af-4ffc-a058-cf7f2227ac15?_state=*****
	Range: 0-21
	X-Content-Type-Options: nosniff
BODY         :

==============================================================================

Expected
    <int>: 202
to equal
    <int>: 416
```

</details>

#### Listing tags

<details>

<summary><b>GET number of tags should be limitable by `n` query parameter</b> docker/distribution#3232 </summary>

To resolve this issue, please see the open pull request [3143](https://github.com/docker/distribution/pull/3143). The returned list of tags must be in lexical order and thus deliver consistend results when the `n` parameter is supplied.

```
2020/07/10 06:16:25.228733 DEBUG
==============================================================================
~~~ REQUEST ~~~
GET  /v2/oci-conformance/distribution-test/tags/list?n=2  HTTP/1.1
HOST   : distribution:5000
HEADERS:
	User-Agent: distribution-spec-conformance-tests
BODY   :
***** NO CONTENT *****
-------------------------------------------------------------2020/07/10 06:16:25.230803 DEBUG
==============================================================================
~~~ REQUEST ~~~
GET  /v2/oci-conformance/distribution-test/tags/list?n=2  HTTP/1.1
HOST   : distribution:5000
HEADERS:
	User-Agent: distribution-spec-conformance-tests
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 200 OK
RECEIVED AT  : 2020-07-10T06:16:25.230528783Z
TIME DURATION: 1.260204ms
HEADERS      :
	Content-Length: 86
	Content-Type: application/json
	Date: Fri, 10 Jul 2020 06:16:25 GMT
	Docker-Distribution-Api-Version: registry/2.0
	X-Content-Type-Options: nosniff
BODY         :
{
   "name": "oci-conformance/distribution-test",
   "tags": [
      "test1",
      "test0",
      "test2",
      "test3"
   ]
}

==============================================================================

2020/07/10 06:16:25.232259 DEBUG
==============================================================================
~~~ REQUEST ~~~
GET  /v2/oci-conformance/distribution-test/tags/list?last=test0&n=2  HTTP/1.1
HOST   : distribution:5000
HEADERS:
	User-Agent: distribution-spec-conformance-tests
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 200 OK
RECEIVED AT  : 2020-07-10T06:16:25.231990686Z
TIME DURATION: 1.130003ms
HEADERS      :
	Content-Length: 86
	Content-Type: application/json
	Date: Fri, 10 Jul 2020 06:16:25 GMT
	Docker-Distribution-Api-Version: registry/2.0
	X-Content-Type-Options: nosniff
BODY         :
{
   "name": "oci-conformance/distribution-test",
   "tags": [
      "test1",
      "test0",
      "test2",
      "test3"
   ]
}

==============================================================================

Expected
    <int>: 4
to be <=
    <int>: 2-----------------
~~~ RESPONSE ~~~
STATUS       : 200 OK
RECEIVED AT  : 2020-07-10T06:16:25.228472177Z
TIME DURATION: 1.173503ms
HEADERS      :
	Content-Length: 86
	Content-Type: application/json
	Date: Fri, 10 Jul 2020 06:16:25 GMT
	Docker-Distribution-Api-Version: registry/2.0
	X-Content-Type-Options: nosniff
BODY         :
{
   "name": "oci-conformance/distribution-test",
   "tags": [
      "test1",
      "test0",
      "test2",
      "test3"
   ]
}

==============================================================================

Expected
    <int>: 4
to equal
    <int>: 2
```

</details>
<details>
<summary><b>GET start of tag is set by `last` query parameter</b> docker/distribution#3233</summary>

To resolve this issue, please see the open pull request [3145](https://github.com/docker/distribution/pull/3145). This must be resolved after the preceding issue in order to return consistent results. Once results are sorted lexically, the `last` query parameter will specify the start (noninclusive) of the subset of `n` tags to be returned.

```
2020/07/10 06:16:25.230803 DEBUG
==============================================================================
~~~ REQUEST ~~~
GET  /v2/oci-conformance/distribution-test/tags/list?n=2  HTTP/1.1
HOST   : distribution:5000
HEADERS:
	User-Agent: distribution-spec-conformance-tests
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 200 OK
RECEIVED AT  : 2020-07-10T06:16:25.230528783Z
TIME DURATION: 1.260204ms
HEADERS      :
	Content-Length: 86
	Content-Type: application/json
	Date: Fri, 10 Jul 2020 06:16:25 GMT
	Docker-Distribution-Api-Version: registry/2.0
	X-Content-Type-Options: nosniff
BODY         :
{
   "name": "oci-conformance/distribution-test",
   "tags": [
      "test1",
      "test0",
      "test2",
      "test3"
   ]
}

==============================================================================

2020/07/10 06:16:25.232259 DEBUG
==============================================================================
~~~ REQUEST ~~~
GET  /v2/oci-conformance/distribution-test/tags/list?last=test0&n=2  HTTP/1.1
HOST   : distribution:5000
HEADERS:
	User-Agent: distribution-spec-conformance-tests
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 200 OK
RECEIVED AT  : 2020-07-10T06:16:25.231990686Z
TIME DURATION: 1.130003ms
HEADERS      :
	Content-Length: 86
	Content-Type: application/json
	Date: Fri, 10 Jul 2020 06:16:25 GMT
	Docker-Distribution-Api-Version: registry/2.0
	X-Content-Type-Options: nosniff
BODY         :
{
   "name": "oci-conformance/distribution-test",
   "tags": [
      "test1",
      "test0",
      "test2",
      "test3"
   ]
}

==============================================================================

Expected
    <int>: 4
to be <=
    <int>: 2
```

</details>

#### Manifest delete

<details>
<summary><b>DELETE request to manifest tag should return 202, unless tag deletion is disallowed (400/405)</b> docker/distribution#3234 </summary>

In order to resolve this issue, you may simply replace the returned `DIGEST_INVALID` with `UNSUPPORTED` since your registry does not support deletion by tag. Optionally, you may want to change the `"message"` to have a more accurate description as to why the request failed.

```
2020/07/10 06:15:58.265521 DEBUG
==============================================================================
~~~ REQUEST ~~~
DELETE  /v2/oci-conformance/distribution-test/manifests/tagtest0  HTTP/1.1
HOST   : distribution:5000
HEADERS:
	User-Agent: distribution-spec-conformance-tests
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 400 Bad Request
RECEIVED AT  : 2020-07-10T06:15:58.265294543Z
TIME DURATION: 2.285498ms
HEADERS      :
	Content-Length: 98
	Content-Type: application/json
	Date: Fri, 10 Jul 2020 06:15:58 GMT
	Docker-Distribution-Api-Version: registry/2.0
	X-Content-Type-Options: nosniff
BODY         :
{
   "errors": [
      {
         "code": "DIGEST_INVALID",
         "message": "provided digest did not match uploaded content"
      }
   ]
}

==============================================================================

Expected
    <string>: DIGEST_INVALID
to equal
    <string>: UNSUPPORTED
```

</details>

## Certification

If this registry is passing the Pull workflow tests (the minimum requirement for certification), you are encouraged to self-certify by submitting conformance test results.

Please see these instructions for more information: https://conformance.opencontainers.org/instructions.html

## Get Involved
If you need help, or feel that these test results are inacurate/outdated, feel free to raise an issue on the following GitHub repository: https://github.com/opencontainers/distribution-spec

The conformance test suite is open-source. You are welcome to propose changes and create pull requests: https://github.com/opencontainers/distribution-spec/tree/master/conformance

Get in contact with the OCI community:

* Slack: https://chat.opencontainers.org/ (#general channel)
* Mailing List: https://groups.google.com/a/opencontainers.org/forum/#!forum/dev

**Comment by thaJeztah** [comment]
I updated the description and split each failure to separate tickets (if no ticket was present yet)

**Comment by jdolitsky** [comment]
It appears that all tests are now passing: https://conformance.opencontainers.org/distribution-spec/#dockerdistribution

<img width="650" alt="Screen Shot 2021-06-14 at 3 01 37 PM" src="https://user-images.githubusercontent.com/393494/121945147-72e29980-cd21-11eb-876f-a5faaab92323.png">

**Comment by wy65701436** [comment]
IMO, the epic can be closed.

**Comment by thaJeztah** [comment]
> IMO, the epic can be closed.

Do we need to verify all the linked issues if they've been addressed (and can be closed)?

**Comment by Jamstah** [comment]
Not sure this can be closed, or at least, not any more.

With the latest conformance tests I get these failures:

```
Summarizing 3 Failures:

[Fail] OCI Distribution Conformance Tests Content Management Manifest delete [It] DELETE request to manifest (digest) should yield 202 response unless already deleted 
/home/jammy/workspaces/integration/distribution-spec/conformance/04_management_test.go:111

[Fail] OCI Distribution Conformance Tests Content Management Blob delete [It] DELETE request to blob URL should yield 202 response 
/home/jammy/workspaces/integration/distribution-spec/conformance/04_management_test.go:150

[Fail] OCI Distribution Conformance Tests Content Management Blob delete [It] GET request to deleted blob URL should yield 404 response 
/home/jammy/workspaces/integration/distribution-spec/conformance/04_management_test.go:165
```

Shall I go ahead and raise issues for them?

**Comment by milosgajdos** [comment]
`DELETE` ones are not required to pass the conformance check I believe.

**Comment by hobbytp** [comment]
@Jamstah @milosgajdos Is there any agreement about the three failed cases? New issues should be raised or should be skipped? Thanks,

**Comment by DavidSpek** [comment]
I believe my PR https://github.com/distribution/distribution/pull/3902 should close the last remaining task here. @milosgajdos would you mind updating the task list so it’s referencing my rebased PR instead of the original so it’s easily traceable?

**Comment by milosgajdos** [comment]
Closing all tasks have now been completed 🎉
